spring:
  application: challnegerbackend
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=Oracle;DEFAULT_NULL_ORDERING=HIGH;NON_KEYWORDS=ID,VALUE;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true

springdoc:
  packagesToScan: com.compass.dev.challengerbackend
  pathsToMatch: /v1, /user